---
- name: Installeer en configureer Apache op LABVM
  hosts: webservers
  become: yes

  vars:
    student_name: "Rohan Gurlek"          # <-- jouw naam
    city_name: "Herzele"                      # <-- jouw woonplaats
    map_iframe_src: "https://www.openstreetmap.org/export/embed.html?bbox=3.8920%2C50.8510%2C3.9560%2C50.9030&layer=mapnik&marker=50.875%2C3.925"
    

  tasks:
    - name: Zorg dat apt cache up-to-date is
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: Installeer Apache webserver (Debian/Ubuntu)
      ansible.builtin.apt:
        name: apache2
        state: present
      when: ansible_facts['os_family'] == "Debian"

    - name: Zorg dat Apache draait en enabled is
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: Plaats eigen home page
      ansible.builtin.template:
        src: index.html.j2
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'
  handlers:
    - name: RESTART APACHE2 
      service:
        name: apache2
        state: restarted 


